name: Build Docs
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]
jobs:
  build-docs:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: ls
      - uses: actions/upload-artifact@v2
        with:
          name: docs-zip
          path: ./docs.zip
